name: docker_data
description: docker_data project
version: 0.0.1
homepage: 
repository: 
environment:
  sdk: ^3.7.2
dependencies:
  global_logger: ^2025.427.1713
  output: ^2025.502.1958
  std: ^2025.504.1244
  sys: ^2025.504.1255
dev_dependencies:
  lints: ^5.1.1
